{"variants":[{"paths":["\/documentation\/gesturedeckios\/pansensitivity\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/!=(_:_:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@GesturedeckiOS@E@PanSensitivity","modules":[{"relatedModules":["Swift"],"name":"GesturedeckiOS"}],"symbolKind":"op","title":"!=(_:_:)","roleHeading":"Operator","role":"symbol","extendedModule":"Swift"},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/Equatable-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/Equatable-Implementations":{"url":"\/documentation\/gesturedeckios\/pansensitivity\/equatable-implementations","title":"Equatable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/Equatable-Implementations","role":"collectionGroup","type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PanSensitivity","kind":"identifier"}],"title":"PanSensitivity","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","navigatorTitle":[{"kind":"identifier","text":"PanSensitivity"}],"url":"\/documentation\/gesturedeckios\/pansensitivity","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/!=(_:_:)":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/!=(_:_:)","type":"topic","title":"!=(_:_:)","kind":"symbol","url":"\/documentation\/gesturedeckios\/pansensitivity\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","kind":"symbol","url":"\/documentation\/gesturedeckios","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"title":"GesturedeckiOS"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/title","value":"PanSensitivity"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/fragments","op":"replace","value":[{"kind":"identifier","text":"PanSensitivity"}]},{"value":[{"kind":"identifier","text":"PanSensitivity"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}