{"kind":"article","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/hashValue"],"anchor":"Instance-Properties","generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/hash(into:)"],"generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"GesturedeckiOS"}],"role":"collectionGroup","title":"RawRepresentable Implementations","roleHeading":"API Collection"},"sections":[],"variants":[{"paths":["\/documentation\/gesturedeckios\/pansensitivity\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity"]]},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","kind":"symbol","url":"\/documentation\/gesturedeckios","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PanSensitivity","kind":"identifier"}],"title":"PanSensitivity","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","navigatorTitle":[{"kind":"identifier","text":"PanSensitivity"}],"url":"\/documentation\/gesturedeckios\/pansensitivity","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/hash(into:)":{"abstract":[],"url":"\/documentation\/gesturedeckios\/pansensitivity\/hash(into:)","kind":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hash(into:)"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/hashValue":{"url":"\/documentation\/gesturedeckios\/pansensitivity\/hashvalue","type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"hashValue","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}},"variantOverrides":[{"patch":[{"value":"PanSensitivity","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/title","op":"replace"},{"value":[{"text":"PanSensitivity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/fragments"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/navigatorTitle","value":[{"text":"PanSensitivity","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}