{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRecognizeSimultaneouslyWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"otherGestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeck\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gesturedeckios\/gesturedeck\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRecognizeSimultaneouslyWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@GesturedeckiOS@objc(cs)Gesturedeck(im)gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","modules":[{"name":"GesturedeckiOS"}],"navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}]},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/UIGestureRecognizerDelegate-Implementations"]]},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)":{"role":"symbol","title":"gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldRecognizeSimultaneouslyWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/gesturerecognizer(_:shouldrecognizesimultaneouslywith:)"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"role":"symbol","title":"Gesturedeck","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesturedeck"}],"abstract":[{"type":"text","text":"A class that provides gesture recognition functionality."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/UIGestureRecognizerDelegate-Implementations":{"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/UIGestureRecognizerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/gesturedeckios\/gesturedeck\/uigesturerecognizerdelegate-implementations"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","title":"GesturedeckiOS","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","kind":"symbol","type":"topic","url":"\/documentation\/gesturedeckios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"gestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRecognizeSimultaneouslyWithGestureRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"otherGestureRecognizer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/title","value":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments","value":[{"kind":"identifier","text":"Gesturedeck"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}