{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hostViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"tapAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"panAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"activationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"autoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"panSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","text":"PanSensitivity"},{"kind":"text","text":" = .medium)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"hostViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller that the gesture recognizer is attached to. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"tapAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that is called when a tap gesture is recognized. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"swipeLeftAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that is called when a left swipe gesture is recognized. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"swipeRightAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that is called when a right swipe gesture is recognized. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"panAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that is called when a pan gesture is recognized. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"panSensitivity","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sensitivity of the pan gestures. Defaults to "},{"type":"codeVoice","code":".medium"},{"type":"text","text":"."}]}]},{"name":"activationKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional activation key to remove watermarks. If not provided, Gesturedeck will present a watermark. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"autoStart","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A boolean indicating whether to automatically start recognizing gestures after initialization. Defaults to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeck\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:longpressaction:activationkey:autostart:pansensitivity:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gesturedeckios\/gesturedeck\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:longpressaction:activationkey:autostart:pansensitivity:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new instance of the "},{"type":"codeVoice","code":"Gesturedeck"},{"type":"text","text":" class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tapAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"panAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"activationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"panSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanSensitivity","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity"},{"kind":"text","text":")"}],"title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@GesturedeckiOS@objc(cs)Gesturedeck(im)initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:","modules":[{"name":"GesturedeckiOS"}],"navigatorTitle":[{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"}]},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck"]]},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity":{"role":"symbol","title":"PanSensitivity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanSensitivity"}],"abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PanSensitivity"}],"url":"\/documentation\/gesturedeckios\/pansensitivity"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"role":"symbol","title":"Gesturedeck","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesturedeck"}],"abstract":[{"type":"text","text":"This is the low-level API that allows you to build custom functionalities on top of Gesturedeck, with seamless callbacks for Gesturedeck’s gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","title":"GesturedeckiOS","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","kind":"symbol","type":"topic","url":"\/documentation\/gesturedeckios"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)":{"role":"symbol","title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tapAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"panAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"activationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"panSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanSensitivity","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new instance of the "},{"type":"codeVoice","code":"Gesturedeck"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:longpressaction:activationkey:autostart:pansensitivity:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initOn:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hostViewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tapAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeLeftAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"swipeLeftAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeRightAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"swipeRightAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"panAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(UIPanGestureRecognizer *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIPanGestureRecognizer)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"panAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"longPressAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(UILongPressGestureRecognizer *)","preciseIdentifier":"c:BFv(#*$objc(cs)UILongPressGestureRecognizer)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"longPressAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"activationKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"activationKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoStart:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoStart"},{"kind":"text","text":" "},{"kind":"identifier","text":"panSensitivity:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","text":"PanSensitivity"},{"kind":"text","text":") "},{"kind":"internalParam","text":"panSensitivity"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/title","value":"PanSensitivity"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/fragments","value":[{"kind":"identifier","text":"PanSensitivity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments","value":[{"kind":"identifier","text":"Gesturedeck"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)\/title","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}