{"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck"]]},"abstract":[{"type":"text","text":"A convenience initializer for the "},{"type":"codeVoice","code":"Gesturedeck"},{"text":" class. You need to set the actions for the corresponsing gestures after initializing.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","modules":[{"name":"GesturedeckiOS"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"symbolKind":"init","role":"symbol","externalID":"c:@M@GesturedeckiOS@objc(cs)Gesturedeck(im)init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeck\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeck\/init()"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init()"},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"A convenience initializer for the ","type":"text"},{"type":"codeVoice","code":"Gesturedeck"},{"text":" class. You need to set the actions for the corresponsing gestures after initializing.","type":"text"}],"title":"init()","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeck\/init()","role":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Gesturedeck","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck","role":"symbol","title":"Gesturedeck","type":"topic","abstract":[{"type":"text","text":"This is the low-level API that allows you to build custom functionalities on top of Gesturedeck, with seamless callbacks for Gesturedeck’s gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"init","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init()\/title","op":"replace","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments","value":[{"text":"Gesturedeck","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}