{"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:"}],"externalID":"c:@M@GesturedeckiOS@objc(cs)Gesturedeck(im)initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:","modules":[{"name":"GesturedeckiOS"}],"symbolKind":"init","title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:)","role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?, ","kind":"text"},{"text":"tapAction","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"swipeRightAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"panAction"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","text":"UIPanGestureRecognizer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?, ","kind":"text"},{"text":"panSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","text":"PanSensitivity"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","text":"UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"autoStart","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"hostViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"? = nil, ","kind":"text"},{"text":"tapAction","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")? = nil, ","kind":"text"},{"text":"swipeLeftAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil, ","kind":"text"},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")? = nil, "},{"text":"panAction","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","text":"UIPanGestureRecognizer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil, ","kind":"text"},{"kind":"externalParam","text":"panSensitivity"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","text":"PanSensitivity","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","kind":"typeIdentifier"},{"kind":"text","text":" = .medium, "},{"kind":"externalParam","text":"longPressAction"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"autoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"activationKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"hostViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller that the gesture recognizer is attached to. Defaults to "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A closure that is called when a tap gesture is recognized. Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"tapAction"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A closure that is called when a left swipe gesture is recognized. Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}],"name":"swipeLeftAction"},{"name":"swipeRightAction","content":[{"inlineContent":[{"type":"text","text":"A closure that is called when a right swipe gesture is recognized. Defaults to "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"panAction","content":[{"type":"paragraph","inlineContent":[{"text":"A closure that is called when a pan gesture is recognized. Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The sensitivity of the pan gestures. Defaults to "},{"type":"codeVoice","code":".medium"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"panSensitivity"},{"name":"longPressAction","content":[{"type":"paragraph","inlineContent":[{"text":"The action to perform when the user long presses the screen. Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},{"name":"autoStart","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A boolean indicating whether to automatically start recognizing gestures after initialization. Defaults to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"An optional activation key to remove watermarks. If not provided, Gesturedeck will present a watermark. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"activationKey"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeck\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:pansensitivity:longpressaction:autostart:activationkey:)"]},{"paths":["\/documentation\/gesturedeckios\/gesturedeck\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:pansensitivity:longpressaction:autostart:activationkey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Initializes a new instance of the ","type":"text"},{"code":"Gesturedeck","type":"codeVoice"},{"text":" class.","type":"text"}],"sections":[],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity":{"title":"PanSensitivity","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PanSensitivity"}],"navigatorTitle":[{"text":"PanSensitivity","kind":"identifier"}],"url":"\/documentation\/gesturedeckios\/pansensitivity","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"type":"topic","role":"collection","abstract":[],"kind":"symbol","url":"\/documentation\/gesturedeckios","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck","title":"Gesturedeck","abstract":[{"type":"text","text":"This is the low-level API that allows you to build custom functionalities on top of Gesturedeck, with seamless callbacks for Gesturedeck’s gestures."}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"tapAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?, ","kind":"text"},{"text":"swipeLeftAction","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"swipeRightAction","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?, "},{"text":"panAction","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","text":"UIPanGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"panSensitivity"},{"text":": ","kind":"text"},{"text":"PanSensitivity","kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity"},{"text":", ","kind":"text"},{"text":"longPressAction","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","text":"UILongPressGestureRecognizer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?, ","kind":"text"},{"text":"autoStart","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"activationKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:pansensitivity:longpressaction:autostart:activationkey:)","role":"symbol","abstract":[{"type":"text","text":"Initializes a new instance of the "},{"type":"codeVoice","code":"Gesturedeck"},{"type":"text","text":" class."}],"title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:)","navigatorTitle":[{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initOn:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"hostViewController"},{"kind":"text","text":" "},{"text":"tapAction:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv()","text":"void (^)(void)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tapAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeLeftAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv()","text":"void (^)(void)"},{"kind":"text","text":") "},{"text":"swipeLeftAction","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeRightAction:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv()","text":"void (^)(void)"},{"kind":"text","text":") "},{"text":"swipeRightAction","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"panAction:"},{"text":"(","kind":"text"},{"text":"void (^)(UIPanGestureRecognizer *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIPanGestureRecognizer)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"panAction"},{"kind":"text","text":" "},{"text":"panSensitivity:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","text":"PanSensitivity","kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"panSensitivity"},{"text":" ","kind":"text"},{"text":"longPressAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(UILongPressGestureRecognizer *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)UILongPressGestureRecognizer)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"longPressAction"},{"kind":"text","text":" "},{"text":"autoStart:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"autoStart"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activationKey:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"activationKey","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PanSensitivity","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PanSensitivity"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck"},{"value":[{"text":"Gesturedeck","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:)\/title","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:activationKey:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}