{"sections":[],"abstract":[{"type":"text","text":"A closure that is called when a right swipe gesture is recognized."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeRightAction"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/swipeRightAction","interfaceLanguage":"swift"},"metadata":{"title":"swipeRightAction","externalID":"c:@M@GesturedeckiOS@objc(cs)Gesturedeck(py)swipeRightAction","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"swipeRightAction","kind":"identifier"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"modules":[{"name":"GesturedeckiOS"}],"symbolKind":"property","navigatorTitle":[{"text":"swipeRightAction","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol"},"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeck\/swiperightaction"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeck\/swiperightaction"]}],"kind":"symbol","references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Gesturedeck","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck","role":"symbol","title":"Gesturedeck","type":"topic","abstract":[{"type":"text","text":"This is the low-level API that allows you to build custom functionalities on top of Gesturedeck, with seamless callbacks for Gesturedeck’s gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/swipeRightAction":{"type":"topic","role":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeck\/swiperightaction","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/swipeRightAction","abstract":[{"type":"text","text":"A closure that is called when a right swipe gesture is recognized."}],"title":"swipeRightAction","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"swipeRightAction","kind":"identifier"},{"kind":"text","text":": (() -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"swipeRightAction","kind":"identifier"}],"kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"swipeRightAction"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"swipeRightAction","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeRightAction"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck","op":"replace"},{"value":[{"text":"Gesturedeck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments"},{"op":"replace","value":"swipeRightAction","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1swipeRightAction\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1swipeRightAction\/fragments","op":"replace","value":[{"kind":"identifier","text":"swipeRightAction"}]}]}]}