{"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/tapAction","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"A closure that is called when a tap gesture is recognized."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tapAction","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck"]]},"metadata":{"title":"tapAction","externalID":"c:@M@GesturedeckiOS@objc(cs)Gesturedeck(py)tapAction","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"GesturedeckiOS"}],"navigatorTitle":[{"text":"tapAction","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tapAction","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeck\/tapaction"]},{"paths":["\/documentation\/gesturedeckios\/gesturedeck\/tapaction"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/tapAction":{"type":"topic","role":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeck\/tapaction","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/tapAction","abstract":[{"type":"text","text":"A closure that is called when a tap gesture is recognized."}],"title":"tapAction","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tapAction","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tapAction"}],"kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Gesturedeck","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck","role":"symbol","title":"Gesturedeck","type":"topic","abstract":[{"type":"text","text":"This is the low-level API that allows you to build custom functionalities on top of Gesturedeck, with seamless callbacks for Gesturedeck’s gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"tapAction","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"tapAction"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv()","text":"void (^)(void)"},{"kind":"text","text":" "},{"text":"tapAction","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"tapAction","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1tapAction\/title"},{"value":[{"kind":"identifier","text":"tapAction"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1tapAction\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck"},{"value":[{"text":"Gesturedeck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}