{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init()","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/gesturedeckMediaOverlay","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/isActive","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/longPressAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/panAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/swipeLeftAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/swipeRightAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/tapAction"]},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/start()","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/stop()"],"title":"Instance Methods"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"GesturedeckMedia"}],"modules":[{"name":"GesturedeckiOS"}],"title":"GesturedeckMedia","role":"symbol","externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMedia","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GesturedeckMedia","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)NSObject","doc:\/\/com.navideck.gesturedeck-ios\/s7CVarArgP","doc:\/\/com.navideck.gesturedeck-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.navideck.gesturedeck-ios\/s23CustomStringConvertibleP","doc:\/\/com.navideck.gesturedeck-ios\/SQ","doc:\/\/com.navideck.gesturedeck-ios\/SH","doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)UIGestureRecognizerDelegate"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GesturedeckMedia"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"inlineContent":[{"text":"Gesturedeck also includes support for media overlays, which can be used to display additional information or controls on top of the app’s content.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/panAction":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"panAction"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A closure that is called when a pan gesture is recognized."}],"navigatorTitle":[{"kind":"identifier","text":"panAction"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/panAction","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/panaction","title":"panAction","role":"symbol","kind":"symbol","type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/longPressAction":{"kind":"symbol","navigatorTitle":[{"text":"longPressAction","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/longPressAction","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/longpressaction","abstract":[{"type":"text","text":"A closure that is called when a long press gesture is recognized."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longPressAction"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","text":"UILongPressGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"type":"topic","title":"longPressAction"},"doc://com.navideck.gesturedeck-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.navideck.gesturedeck-ios/SH":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SH","title":"Swift.Hashable"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GesturedeckMedia","kind":"identifier"}],"type":"topic","title":"GesturedeckMedia","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GesturedeckMedia","kind":"identifier"}]},"doc://com.navideck.gesturedeck-ios/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Gesturedeck","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck","role":"symbol","title":"Gesturedeck","type":"topic","abstract":[{"type":"text","text":"This is the low-level API that allows you to build custom functionalities on top of Gesturedeck, with seamless callbacks for Gesturedeck’s gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/tapAction":{"navigatorTitle":[{"kind":"identifier","text":"tapAction"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/tapaction","type":"topic","abstract":[{"type":"text","text":"A closure that is called when a tap gesture is recognized."}],"title":"tapAction","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/tapAction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tapAction","kind":"identifier"},{"kind":"text","text":": (() -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"role":"symbol","kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/swipeLeftAction":{"kind":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/swipeleftaction","navigatorTitle":[{"text":"swipeLeftAction","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeLeftAction"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"title":"swipeLeftAction","type":"topic","abstract":[{"type":"text","text":"A closure that is called when a left swipe gesture is recognized."}],"role":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/swipeLeftAction"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/isActive":{"role":"symbol","abstract":[{"text":"Determines whether the gesture recognizer is active.","type":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/isactive","navigatorTitle":[{"text":"isActive","kind":"identifier"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/isActive","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isActive"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isActive","kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)":{"navigatorTitle":[{"text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:","kind":"identifier"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)","role":"symbol","abstract":[{"type":"text","text":"Initializes a new instance of GesturedeckMedia."},{"type":"text","text":" "},{"text":"You can initialize GesturedeckMedia without any arguments and have start\/stop, skip next\/previous and volume up\/down work out of the box.","type":"text"}],"type":"topic","title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tapAction"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"swipeLeftAction"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"panAction","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"text":"UIPanGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"panSensitivity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","kind":"typeIdentifier","text":"PanSensitivity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","text":"UILongPressGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?, "},{"text":"autoStart","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gesturedeckMediaOverlay"},{"kind":"text","text":": "},{"text":"GesturedeckMediaOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"activationKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:pansensitivity:longpressaction:autostart:gesturedeckmediaoverlay:activationkey:)"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/init()":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"A convenience initializer for the "},{"type":"codeVoice","code":"GesturedeckMedia"},{"text":" class.","type":"text"},{"text":" ","type":"text"},{"text":"You can initialize GesturedeckMedia without any arguments and have start\/stop, skip next\/previous and volume up\/down work out of the box.","type":"text"},{"type":"text","text":" "},{"text":"Note that due to iOS limitations, skip next\/previous only works for the system media player.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/init()","role":"symbol","title":"init()"},"doc://com.navideck.gesturedeck-ios/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.navideck.gesturedeck-ios/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SQ","title":"Swift.Equatable"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/start()":{"abstract":[{"type":"text","text":"Starts the gesture recognizer."}],"type":"topic","title":"start()","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/start()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"start","kind":"identifier"}],"role":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/start()"},"doc://com.navideck.gesturedeck-ios/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)UIGestureRecognizerDelegate","title":"UIKit.UIGestureRecognizerDelegate"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/swipeRightAction":{"type":"topic","title":"swipeRightAction","navigatorTitle":[{"kind":"identifier","text":"swipeRightAction"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/swiperightaction","abstract":[{"type":"text","text":"A closure that is called when a right swipe gesture is recognized."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"swipeRightAction","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/swipeRightAction"},"doc://com.navideck.gesturedeck-ios/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/stop()":{"role":"symbol","abstract":[{"text":"Stops the gesture recognizer.","type":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/stop()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"title":"stop()","kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/gesturedeckMediaOverlay":{"kind":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/gesturedeckmediaoverlay","title":"gesturedeckMediaOverlay","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gesturedeckMediaOverlay"},{"text":": ","kind":"text"},{"text":"GesturedeckMediaOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/gesturedeckMediaOverlay","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"gesturedeckMediaOverlay"}],"abstract":[{"type":"text","text":"The overlay view that displays media-related gestures."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"GesturedeckMedia","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"GesturedeckMedia","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"GesturedeckMedia","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/gesturedeckMediaOverlay","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/isActive","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/longPressAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/panAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/swipeLeftAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/swipeRightAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/tapAction"]},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init()","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/start()","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/stop()"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"GesturedeckMedia","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Gesturedeck","kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)Gesturedeck","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck"}],"languages":["occ"]}]},"op":"replace"},{"value":"panAction","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1panAction\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1panAction\/fragments","op":"replace","value":[{"kind":"identifier","text":"panAction"}]},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1longPressAction\/title","value":"longPressAction","op":"replace"},{"value":[{"text":"longPressAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1longPressAction\/fragments","op":"replace"},{"value":"GesturedeckMedia","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments","op":"replace","value":[{"text":"GesturedeckMedia","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck"},{"value":[{"text":"Gesturedeck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments"},{"op":"replace","value":"tapAction","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1tapAction\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1tapAction\/fragments","value":[{"text":"tapAction","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"swipeLeftAction","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1swipeLeftAction\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1swipeLeftAction\/fragments","value":[{"text":"swipeLeftAction","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1isActive\/title","value":"isActive"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1isActive\/fragments","value":[{"kind":"identifier","text":"isActive"}]},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)\/title","op":"replace","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:","kind":"identifier"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"replace","value":"start","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1start()\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1start()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}],"op":"replace"},{"value":"swipeRightAction","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1swipeRightAction\/title"},{"op":"replace","value":[{"kind":"identifier","text":"swipeRightAction"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1swipeRightAction\/fragments"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1stop()\/title","value":"stop","op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1stop()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stop"}],"op":"replace"},{"op":"replace","value":"gesturedeckMediaOverlay","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1gesturedeckMediaOverlay\/title"},{"op":"replace","value":[{"text":"gesturedeckMediaOverlay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1gesturedeckMediaOverlay\/fragments"}]}]}