{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesturedeck"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeck"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gesturedeckios\/gesturedeck"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)NSObject","doc:\/\/com.navideck.gesturedeck-ios\/s7CVarArgP","doc:\/\/com.navideck.gesturedeck-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.navideck.gesturedeck-ios\/s23CustomStringConvertibleP","doc:\/\/com.navideck.gesturedeck-ios\/SQ","doc:\/\/com.navideck.gesturedeck-ios\/SH","doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)UIGestureRecognizerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A class that provides gesture recognition functionality."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesturedeck"}],"title":"Gesturedeck","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GesturedeckiOS@objc(cs)Gesturedeck","modules":[{"name":"GesturedeckiOS"}],"navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}]},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init()","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/isActive","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/longPressAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/panAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/panSensitivity","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/swipeLeftAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/swipeRightAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/tapAction"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/start()","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/stop()"]}],"references":{"doc://com.navideck.gesturedeck-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s23CustomStringConvertibleP"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:":{"role":"symbol","title":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}],"abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/gesturerecognizer:shouldrecognizesimultaneouslywithgesturerecognizer:"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"role":"symbol","title":"GesturedeckMedia","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GesturedeckMedia"}],"abstract":[{"type":"text","text":"A subclass of Gesturedeck that adds media-related gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GesturedeckMedia"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/panAction":{"role":"symbol","title":"panAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"panAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A closure that is called when a pan gesture is recognized."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/panAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"panAction"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/panaction"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/gestureRecognizerShouldBegin:":{"role":"symbol","title":"gestureRecognizerShouldBegin:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/gestureRecognizerShouldBegin:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/gesturerecognizershouldbegin:"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/tapAction":{"role":"symbol","title":"tapAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A closure that is called when a tap gesture is recognized."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/tapAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tapAction"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/tapaction"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","title":"GesturedeckiOS","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","kind":"symbol","type":"topic","url":"\/documentation\/gesturedeckios"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/swipeRightAction":{"role":"symbol","title":"swipeRightAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A closure that is called when a right swipe gesture is recognized."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/swipeRightAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"swipeRightAction"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/swiperightaction"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/start()":{"role":"symbol","title":"start()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts the gesture recognizer."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/start()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/start()"},"doc://com.navideck.gesturedeck-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SH"},"doc://com.navideck.gesturedeck-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SQ"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/isActive":{"role":"symbol","title":"isActive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines whether the gesture recognizer is active."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/isActive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isActive"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/isactive"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"A convenience initializer for the "},{"type":"codeVoice","code":"Gesturedeck"},{"type":"text","text":" class. You need to set the actions for the corresponsing gestures after initializing."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/init()"},"doc://com.navideck.gesturedeck-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s28CustomDebugStringConvertibleP"},"doc://com.navideck.gesturedeck-ios/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIGestureRecognizerDelegate","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.navideck.gesturedeck-ios/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)NSObject"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)":{"role":"symbol","title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tapAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"panAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"activationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"panSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanSensitivity","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new instance of the "},{"type":"codeVoice","code":"Gesturedeck"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:longpressaction:activationkey:autostart:pansensitivity:)"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/swipeLeftAction":{"role":"symbol","title":"swipeLeftAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A closure that is called when a left swipe gesture is recognized."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/swipeLeftAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"swipeLeftAction"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/swipeleftaction"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"role":"symbol","title":"Gesturedeck","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesturedeck"}],"abstract":[{"type":"text","text":"A class that provides gesture recognition functionality."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/longPressAction":{"role":"symbol","title":"longPressAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longPressAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A closure that is called when a long press gesture is recognized."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/longPressAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"longPressAction"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/longpressaction"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/stop()":{"role":"symbol","title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the gesture recognizer."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/stop()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stop"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/stop()"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck/panSensitivity":{"role":"symbol","title":"panSensitivity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"panSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PanSensitivity","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity"}],"abstract":[{"type":"text","text":"The sensitivity of the pan gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/panSensitivity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"panSensitivity"}],"url":"\/documentation\/gesturedeckios\/gesturedeck\/pansensitivity"},"doc://com.navideck.gesturedeck-ios/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/objc(cs)NSObject"},"doc://com.navideck.gesturedeck-ios/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Gesturedeck"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Gesturedeck"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Gesturedeck"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/isActive","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/longPressAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/panAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/panSensitivity","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/swipeLeftAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/swipeRightAction","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/tapAction"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/gestureRecognizerShouldBegin:","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init()","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/start()","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck\/stop()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)UIGestureRecognizerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Gesturedeck"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title","value":"GesturedeckMedia"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments","value":[{"kind":"identifier","text":"GesturedeckMedia"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1panAction\/title","value":"panAction"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1panAction\/fragments","value":[{"kind":"identifier","text":"panAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1tapAction\/title","value":"tapAction"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1tapAction\/fragments","value":[{"kind":"identifier","text":"tapAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1swipeRightAction\/title","value":"swipeRightAction"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1swipeRightAction\/fragments","value":[{"kind":"identifier","text":"swipeRightAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1start()\/title","value":"start"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1start()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1isActive\/title","value":"isActive"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1isActive\/fragments","value":[{"kind":"identifier","text":"isActive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)\/title","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:panSensitivity:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1swipeLeftAction\/title","value":"swipeLeftAction"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1swipeLeftAction\/fragments","value":[{"kind":"identifier","text":"swipeLeftAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments","value":[{"kind":"identifier","text":"Gesturedeck"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1longPressAction\/title","value":"longPressAction"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1longPressAction\/fragments","value":[{"kind":"identifier","text":"longPressAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1stop()\/title","value":"stop"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1stop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1panSensitivity\/title","value":"panSensitivity"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck~1panSensitivity\/fragments","value":[{"kind":"identifier","text":"panSensitivity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}