{"relationshipsSections":[{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)NSObject","doc:\/\/com.navideck.gesturedeck-ios\/s7CVarArgP","doc:\/\/com.navideck.gesturedeck-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.navideck.gesturedeck-ios\/s23CustomStringConvertibleP","doc:\/\/com.navideck.gesturedeck-ios\/SQ","doc:\/\/com.navideck.gesturedeck-ios\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"metadata":{"modules":[{"name":"GesturedeckiOS"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay","role":"symbol","symbolKind":"class","title":"GesturedeckMediaOverlay","navigatorTitle":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"roleHeading":"Class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay"]},{"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)"],"title":"Initializers","anchor":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/backgroundColor","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/centerIconShowsOuterRing","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconSwipeLeft","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconSwipeRight","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconTap","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconTapToggled","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/reverseHorizontalSwipes","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/tintColor","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/topIcon"],"title":"Instance Properties"}],"references":{"doc://com.navideck.gesturedeck-ios/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/centerIconShowsOuterRing":{"abstract":[{"text":"A Boolean value that determines whether the center icon shows the outer ring.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/centerIconShowsOuterRing","title":"centerIconShowsOuterRing","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"centerIconShowsOuterRing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/centericonshowsouterring","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"centerIconShowsOuterRing"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/iconTapToggled":{"type":"topic","title":"iconTapToggled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iconTapToggled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/icontaptoggled","abstract":[{"type":"text","text":"The icon for toggling the tap on the media overlay."}],"kind":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconTapToggled","navigatorTitle":[{"text":"iconTapToggled","kind":"identifier"}]},"doc://com.navideck.gesturedeck-ios/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/topIcon":{"type":"topic","title":"topIcon","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topIcon","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/topicon","abstract":[{"text":"The top icon of the media overlay.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/topIcon","navigatorTitle":[{"text":"topIcon","kind":"identifier"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","kind":"symbol","url":"\/documentation\/gesturedeckios","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/iconSwipeRight":{"abstract":[{"type":"text","text":"The icon for swiping right on the media overlay."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconSwipeRight","title":"iconSwipeRight","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconSwipeRight"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/iconswiperight","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"iconSwipeRight"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","role":"symbol","type":"topic","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/init(tintcolor:backgroundcolor:topicon:icontap:icontaptoggled:iconswipeleft:iconswiperight:reversehorizontalswipes:centericonshowsouterring:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"topIcon"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"iconTapToggled"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"iconSwipeLeft","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?, "},{"text":"iconSwipeRight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"reverseHorizontalSwipes","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"centerIconShowsOuterRing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:","kind":"identifier"}],"title":"init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","kind":"symbol","abstract":[{"type":"text","text":"Initializes a new instance of the "},{"code":"GesturedeckMediaOverlay","type":"codeVoice"},{"type":"text","text":" struct."}]},"doc://com.navideck.gesturedeck-ios/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SQ","title":"Swift.Equatable"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/reverseHorizontalSwipes":{"abstract":[{"type":"text","text":"A Boolean value that determines whether horizontal swipes are reversed."}],"role":"symbol","title":"reverseHorizontalSwipes","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/reverseHorizontalSwipes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reverseHorizontalSwipes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/reversehorizontalswipes","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"reverseHorizontalSwipes"}]},"doc://com.navideck.gesturedeck-ios/SH":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/tintColor":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/tintColor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tintColor"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tintColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","abstract":[{"text":"The color used to tint the overlay elements. Has effect only when an activation key is set.","type":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/tintcolor","title":"tintColor"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/iconSwipeLeft":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconSwipeLeft"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"iconSwipeLeft","kind":"identifier"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconSwipeLeft","title":"iconSwipeLeft","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"The icon for swiping left on the media overlay.","type":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/iconswipeleft"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/iconTap":{"kind":"symbol","type":"topic","title":"iconTap","abstract":[{"text":"The icon for tapping on the media overlay.","type":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconTap","role":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/icontap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"iconTap","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"iconTap"}]},"doc://com.navideck.gesturedeck-ios/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s7CVarArgP"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/backgroundColor":{"kind":"symbol","type":"topic","title":"backgroundColor","abstract":[{"text":"The background color of the media overlay","type":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/backgroundColor","role":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/backgroundcolor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}]},"doc://com.navideck.gesturedeck-ios/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/objc(cs)NSObject","title":"NSObject"},"doc://com.navideck.gesturedeck-ios/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/s28CustomDebugStringConvertibleP"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","title":"GesturedeckMediaOverlay","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GesturedeckMediaOverlay","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/backgroundColor","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/centerIconShowsOuterRing","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconSwipeLeft","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconSwipeRight","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconTap","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconTapToggled","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/reverseHorizontalSwipes","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/tintColor","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/topIcon"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GesturedeckMediaOverlay"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1centerIconShowsOuterRing\/title","value":"centerIconShowsOuterRing"},{"op":"replace","value":[{"text":"centerIconShowsOuterRing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1centerIconShowsOuterRing\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconTapToggled\/title","value":"iconTapToggled"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconTapToggled\/fragments","value":[{"text":"iconTapToggled","kind":"identifier"}]},{"op":"replace","value":"topIcon","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1topIcon\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1topIcon\/fragments","value":[{"text":"topIcon","kind":"identifier"}]},{"op":"replace","value":"iconSwipeRight","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconSwipeRight\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconSwipeRight\/fragments","value":[{"text":"iconSwipeRight","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)\/title","value":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1reverseHorizontalSwipes\/title","value":"reverseHorizontalSwipes"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1reverseHorizontalSwipes\/fragments","op":"replace","value":[{"kind":"identifier","text":"reverseHorizontalSwipes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1tintColor\/title","value":"tintColor"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1tintColor\/fragments","value":[{"text":"tintColor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconSwipeLeft\/title","value":"iconSwipeLeft","op":"replace"},{"value":[{"text":"iconSwipeLeft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconSwipeLeft\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconTap\/title","value":"iconTap"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconTap\/fragments","value":[{"text":"iconTap","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"backgroundColor","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1backgroundColor\/title"},{"op":"replace","value":[{"text":"backgroundColor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1backgroundColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title","value":"GesturedeckMediaOverlay"},{"value":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/navigatorTitle","op":"replace","value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}]}]}]}