{"metadata":{"externalID":"c:@M@GesturedeckiOS@E@PanSensitivity","title":"PanSensitivity","modules":[{"name":"GesturedeckiOS"}],"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PanSensitivity"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PanSensitivity"}],"roleHeading":"Enumeration"},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/high","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/low","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/medium"]},{"title":"Initializers","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/Equatable-Implementations","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/RawRepresentable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/pansensitivity"]},{"paths":["\/documentation\/gesturedeckios\/pansensitivity"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PanSensitivity","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/SQ","doc:\/\/com.navideck.gesturedeck-ios\/SH","doc:\/\/com.navideck.gesturedeck-ios\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS"]]},"references":{"doc://com.navideck.gesturedeck-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SH"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/medium":{"role":"symbol","abstract":[],"url":"\/documentation\/gesturedeckios\/pansensitivity\/medium","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/medium","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"medium"}],"title":"PanSensitivity.medium","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PanSensitivityMedium"}],"type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/init(rawValue:)":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/init(rawValue:)","role":"symbol","url":"\/documentation\/gesturedeckios\/pansensitivity\/init(rawvalue:)","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/high":{"navigatorTitle":[{"kind":"identifier","text":"PanSensitivityHigh"}],"url":"\/documentation\/gesturedeckios\/pansensitivity\/high","kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/high","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"high"}],"title":"PanSensitivity.high"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity":{"url":"\/documentation\/gesturedeckios\/pansensitivity","kind":"symbol","role":"symbol","title":"PanSensitivity","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PanSensitivity","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","navigatorTitle":[{"kind":"identifier","text":"PanSensitivity"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/low":{"url":"\/documentation\/gesturedeckios\/pansensitivity\/low","kind":"symbol","role":"symbol","title":"PanSensitivity.low","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"low"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/low","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PanSensitivityLow"}]},"doc://com.navideck.gesturedeck-ios/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SQ"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/RawRepresentable-Implementations":{"kind":"article","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/gesturedeckios\/pansensitivity\/rawrepresentable-implementations"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity/Equatable-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/Equatable-Implementations","url":"\/documentation\/gesturedeckios\/pansensitivity\/equatable-implementations"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"},"doc://com.navideck.gesturedeck-ios/SY":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/SY","title":"Swift.RawRepresentable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PanSensitivity","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PanSensitivity","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"PanSensitivity"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/high","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/low","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity\/medium"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PanSensitivity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity~1medium\/title","value":"PanSensitivityMedium"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity~1medium\/fragments","value":[{"text":"PanSensitivityMedium","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity~1high\/title","op":"replace","value":"PanSensitivityHigh"},{"value":[{"text":"PanSensitivityHigh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity~1high\/fragments"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/title","value":"PanSensitivity","op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/fragments","value":[{"kind":"identifier","text":"PanSensitivity"}],"op":"replace"},{"op":"replace","value":"PanSensitivityLow","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity~1low\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity~1low\/fragments","value":[{"text":"PanSensitivityLow","kind":"identifier"}]}]}]}