{"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"]},{"title":"Enumerations","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity"]}],"metadata":{"role":"collection","symbolKind":"module","modules":[{"name":"GesturedeckiOS"}],"roleHeading":"Framework","title":"GesturedeckiOS","externalID":"GesturedeckiOS"},"variants":[{"paths":["\/documentation\/gesturedeckios"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios"]}],"hierarchy":{"paths":[[]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GesturedeckMedia","kind":"identifier"}],"type":"topic","title":"GesturedeckMedia","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GesturedeckMedia","kind":"identifier"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity":{"url":"\/documentation\/gesturedeckios\/pansensitivity","kind":"symbol","role":"symbol","title":"PanSensitivity","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PanSensitivity","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","navigatorTitle":[{"kind":"identifier","text":"PanSensitivity"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckVersionString":{"type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckVersionString","role":"symbol","fragments":[{"kind":"identifier","text":"GesturedeckVersionString"}],"url":"\/documentation\/gesturedeckios\/gesturedeckversionstring","abstract":[{"text":"Project version string for Gesturedeck.","type":"text"}],"kind":"symbol","title":"GesturedeckVersionString"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/Gesturedeck":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Gesturedeck","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Gesturedeck"}],"url":"\/documentation\/gesturedeckios\/gesturedeck","role":"symbol","title":"Gesturedeck","type":"topic","abstract":[{"type":"text","text":"This is the low-level API that allows you to build custom functionalities on top of Gesturedeck, with seamless callbacks for Gesturedeck’s gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","kind":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic","title":"GesturedeckMediaOverlay","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckVersionNumber":{"kind":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckVersionNumber","url":"\/documentation\/gesturedeckios\/gesturedeckversionnumber","role":"symbol","fragments":[{"kind":"identifier","text":"GesturedeckVersionNumber"}],"title":"GesturedeckVersionNumber","abstract":[{"text":"Project version number for Gesturedeck.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Classes","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/Gesturedeck","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"]},{"title":"Variables","identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckVersionNumber","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckVersionString"]},{"identifiers":["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity"],"title":"Enumerations"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"GesturedeckMedia","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title"},{"op":"replace","value":[{"text":"GesturedeckMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/title","value":"PanSensitivity","op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/fragments","op":"replace","value":[{"text":"PanSensitivity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/title","value":"Gesturedeck","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1Gesturedeck\/fragments","value":[{"text":"Gesturedeck","kind":"identifier"}]},{"value":"GesturedeckMediaOverlay","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments","value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}]}]}]}