{"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"]]},"metadata":{"navigatorTitle":[{"text":"iconTapToggled","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"iconTapToggled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"title":"iconTapToggled","role":"symbol","modules":[{"name":"GesturedeckiOS"}],"symbolKind":"property","externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay(py)iconTapToggled"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconTapToggled"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/icontaptoggled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/icontaptoggled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"iconTapToggled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The icon for toggling the tap on the media overlay."}],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic","title":"GesturedeckMediaOverlay","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/iconTapToggled":{"kind":"symbol","abstract":[{"text":"The icon for toggling the tap on the media overlay.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconTapToggled"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"iconTapToggled","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconTapToggled","navigatorTitle":[{"kind":"identifier","text":"iconTapToggled"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/icontaptoggled","type":"topic","role":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"iconTapToggled"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"iconTapToggled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"iconTapToggled","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title","value":"GesturedeckMediaOverlay"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments","value":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconTapToggled\/title","value":"iconTapToggled"},{"value":[{"kind":"identifier","text":"iconTapToggled"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconTapToggled\/fragments"}]}]}