{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconSwipeLeft"},"abstract":[{"type":"text","text":"The icon for swiping left on the media overlay."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iconSwipeLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/iconswipeleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/iconswipeleft"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","modules":[{"name":"GesturedeckiOS"}],"role":"symbol","roleHeading":"Instance Property","title":"iconSwipeLeft","navigatorTitle":[{"text":"iconSwipeLeft","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iconSwipeLeft"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay(py)iconSwipeLeft"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"]]},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/iconSwipeLeft":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"iconSwipeLeft","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/iconSwipeLeft","title":"iconSwipeLeft","abstract":[{"type":"text","text":"The icon for swiping left on the media overlay."}],"role":"symbol","navigatorTitle":[{"text":"iconSwipeLeft","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/iconswipeleft","type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","title":"GesturedeckMediaOverlay","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","kind":"symbol","url":"\/documentation\/gesturedeckios","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"title":"GesturedeckiOS"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"iconSwipeLeft","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"iconSwipeLeft","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"iconSwipeLeft","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconSwipeLeft\/title","value":"iconSwipeLeft"},{"op":"replace","value":[{"kind":"identifier","text":"iconSwipeLeft"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1iconSwipeLeft\/fragments"},{"op":"replace","value":"GesturedeckMediaOverlay","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments","value":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}]},{"op":"replace","value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/navigatorTitle"}]}]}