{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"? = nil, ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"topIcon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"? = nil, ","kind":"text"},{"text":"iconTap","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"iconTapToggled"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"iconSwipeLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"iconSwipeRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"reverseHorizontalSwipes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"centerIconShowsOuterRing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true)"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tint color of the media overlay."}]}],"name":"tintColor"},{"name":"backgroundColor","content":[{"type":"paragraph","inlineContent":[{"text":"The background color of the media overlay","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The top icon of the media overlay.","type":"text"}],"type":"paragraph"}],"name":"topIcon"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The icon for tapping on the media overlay."}]}],"name":"iconTap"},{"content":[{"inlineContent":[{"type":"text","text":"The icon for toggling the tap on the media overlay."}],"type":"paragraph"}],"name":"iconTapToggled"},{"name":"iconSwipeLeft","content":[{"inlineContent":[{"type":"text","text":"The icon for swiping left on the media overlay."}],"type":"paragraph"}]},{"name":"iconSwipeRight","content":[{"type":"paragraph","inlineContent":[{"text":"The icon for swiping right on the media overlay.","type":"text"}]}]},{"name":"reverseHorizontalSwipes","content":[{"inlineContent":[{"text":"A Boolean value that determines whether horizontal swipes are reversed.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"A Boolean value that determines whether the center icon shows the outer ring."}],"type":"paragraph"}],"name":"centerIconShowsOuterRing"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"]]},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"init","externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay(im)initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:","title":"init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","modules":[{"name":"GesturedeckiOS"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tintColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"text":"topIcon","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"text":"iconTap","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"iconTapToggled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"iconSwipeLeft","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconSwipeRight"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"reverseHorizontalSwipes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"centerIconShowsOuterRing"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Initializer"},"abstract":[{"text":"Initializes a new instance of the ","type":"text"},{"code":"GesturedeckMediaOverlay","type":"codeVoice"},{"type":"text","text":" struct."}],"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/init(tintcolor:backgroundcolor:topicon:icontap:icontaptoggled:iconswipeleft:iconswiperight:reversehorizontalswipes:centericonshowsouterring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/init(tintcolor:backgroundcolor:topicon:icontap:icontaptoggled:iconswipeleft:iconswiperight:reversehorizontalswipes:centericonshowsouterring:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)":{"abstract":[{"text":"Initializes a new instance of the ","type":"text"},{"type":"codeVoice","code":"GesturedeckMediaOverlay"},{"type":"text","text":" struct."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","role":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/init(tintcolor:backgroundcolor:topicon:icontap:icontaptoggled:iconswipeleft:iconswiperight:reversehorizontalswipes:centericonshowsouterring:)","title":"init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tintColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?, "},{"text":"topIcon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"iconTap","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"iconTapToggled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"iconSwipeLeft"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"text":"iconSwipeRight","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"reverseHorizontalSwipes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"centerIconShowsOuterRing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"type":"topic","role":"collection","abstract":[],"kind":"symbol","url":"\/documentation\/gesturedeckios","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"title":"GesturedeckMediaOverlay","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","kind":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","abstract":[{"text":"A struct that represents the media overlay for Gesturedeck.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTintColor:"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tintColor"},{"text":" ","kind":"text"},{"text":"backgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" *) "},{"text":"backgroundColor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"topIcon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"topIcon","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconTap:"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"iconTap","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconTapToggled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"iconTapToggled"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconSwipeLeft:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"iconSwipeLeft"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iconSwipeRight:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"iconSwipeRight"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverseHorizontalSwipes:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"reverseHorizontalSwipes"},{"text":" ","kind":"text"},{"text":"centerIconShowsOuterRing:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"centerIconShowsOuterRing","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1init(tintColor:backgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)\/fragments"},{"value":"GesturedeckMediaOverlay","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title"},{"op":"replace","value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments"}]}]}