{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"overlayBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"topIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"iconTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"iconTapToggled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"iconSwipeLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"iconSwipeRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"reverseHorizontalSwipes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"centerIconShowsOuterRing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"tintColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tint color of the media overlay."}]}]},{"name":"overlayBackgroundColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The background color of the media overlay"}]}]},{"name":"topIcon","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The top icon of the media overlay."}]}]},{"name":"iconTap","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The icon for tapping on the media overlay."}]}]},{"name":"iconTapToggled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The icon for toggling the tap on the media overlay."}]}]},{"name":"iconSwipeLeft","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The icon for swiping left on the media overlay."}]}]},{"name":"iconSwipeRight","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The icon for swiping right on the media overlay."}]}]},{"name":"reverseHorizontalSwipes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Boolean value that determines whether horizontal swipes are reversed."}]}]},{"name":"centerIconShowsOuterRing","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Boolean value that determines whether the center icon shows the outer ring."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/init(tintcolor:overlaybackgroundcolor:topicon:icontap:icontaptoggled:iconswipeleft:iconswiperight:reversehorizontalswipes:centericonshowsouterring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/init(tintcolor:overlaybackgroundcolor:topicon:icontap:icontaptoggled:iconswipeleft:iconswiperight:reversehorizontalswipes:centericonshowsouterring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/init(tintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new instance of the "},{"type":"codeVoice","code":"GesturedeckMediaOverlay"},{"type":"text","text":" struct."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"overlayBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"topIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconTapToggled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconSwipeLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconSwipeRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"reverseHorizontalSwipes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"centerIconShowsOuterRing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(tintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay(im)initWithTintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:","modules":[{"name":"GesturedeckiOS"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}]},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"]]},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"role":"symbol","title":"GesturedeckMediaOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/init(tintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)":{"role":"symbol","title":"init(tintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"overlayBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"topIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconTap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconTapToggled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconSwipeLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"iconSwipeRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"reverseHorizontalSwipes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"centerIconShowsOuterRing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new instance of the "},{"type":"codeVoice","code":"GesturedeckMediaOverlay"},{"type":"text","text":" struct."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/init(tintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/init(tintcolor:overlaybackgroundcolor:topicon:icontap:icontaptoggled:iconswipeleft:iconswiperight:reversehorizontalswipes:centericonshowsouterring:)"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","title":"GesturedeckiOS","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","kind":"symbol","type":"topic","url":"\/documentation\/gesturedeckios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithTintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTintColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tintColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"overlayBackgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"topIcon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topIcon"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconTap:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"iconTap"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconTapToggled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"iconTapToggled"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconSwipeLeft:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"iconSwipeLeft"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconSwipeRight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"iconSwipeRight"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverseHorizontalSwipes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"reverseHorizontalSwipes"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerIconShowsOuterRing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"centerIconShowsOuterRing"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title","value":"GesturedeckMediaOverlay"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments","value":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1init(tintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)\/title","value":"initWithTintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1init(tintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTintColor:overlayBackgroundColor:topIcon:iconTap:iconTapToggled:iconSwipeLeft:iconSwipeRight:reverseHorizontalSwipes:centerIconShowsOuterRing:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}