{"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"reverseHorizontalSwipes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"reverseHorizontalSwipes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"reverseHorizontalSwipes","navigatorTitle":[{"text":"reverseHorizontalSwipes","kind":"identifier"}],"externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay(py)reverseHorizontalSwipes","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"GesturedeckiOS"}]},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/reverseHorizontalSwipes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Boolean value that determines whether horizontal swipes are reversed."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/reversehorizontalswipes"]},{"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/reversehorizontalswipes"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic","title":"GesturedeckMediaOverlay","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}]},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/reverseHorizontalSwipes":{"title":"reverseHorizontalSwipes","kind":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/reversehorizontalswipes","abstract":[{"type":"text","text":"A Boolean value that determines whether horizontal swipes are reversed."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverseHorizontalSwipes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"reverseHorizontalSwipes"}],"type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/reverseHorizontalSwipes"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"reverseHorizontalSwipes","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"reverseHorizontalSwipes"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"reverseHorizontalSwipes","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title","value":"GesturedeckMediaOverlay","op":"replace"},{"value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments"},{"value":"reverseHorizontalSwipes","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1reverseHorizontalSwipes\/title"},{"value":[{"text":"reverseHorizontalSwipes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1reverseHorizontalSwipes\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}