{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/tintColor"},"abstract":[{"type":"text","text":"The color used to tint the overlay elements. Has effect only when an activation key is set."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/tintcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/tintcolor"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tintColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"tintColor","kind":"identifier"}],"roleHeading":"Instance Property","title":"tintColor","role":"symbol","modules":[{"name":"GesturedeckiOS"}],"externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay(py)tintColor","symbolKind":"property"},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","kind":"symbol","url":"\/documentation\/gesturedeckios","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay/tintColor":{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay\/tintColor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tintColor"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tintColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","abstract":[{"text":"The color used to tint the overlay elements. Has effect only when an activation key is set.","type":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay\/tintcolor","title":"tintColor"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","title":"GesturedeckMediaOverlay","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"tintColor","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"tintColor","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"tintColor"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"tintColor","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1tintColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"tintColor"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay~1tintColor\/fragments"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title","op":"replace","value":"GesturedeckMediaOverlay"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments","value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/navigatorTitle","value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}