{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gesturedeckMediaOverlay","kind":"identifier"},{"kind":"text","text":": "},{"text":"GesturedeckMediaOverlay","kind":"typeIdentifier","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/gesturedeckMediaOverlay","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMedia(py)gesturedeckMediaOverlay","modules":[{"name":"GesturedeckiOS"}],"symbolKind":"property","navigatorTitle":[{"text":"gesturedeckMediaOverlay","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"gesturedeckMediaOverlay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay","text":"GesturedeckMediaOverlay","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"gesturedeckMediaOverlay","role":"symbol"},"abstract":[{"text":"The overlay view that displays media-related gestures.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/gesturedeckmediaoverlay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/gesturedeckmediaoverlay"]}],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"title":"GesturedeckMediaOverlay","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","kind":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","abstract":[{"text":"A struct that represents the media overlay for Gesturedeck.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"type":"topic","role":"collection","abstract":[],"kind":"symbol","url":"\/documentation\/gesturedeckios","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GesturedeckMedia"}],"abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","navigatorTitle":[{"text":"GesturedeckMedia","kind":"identifier"}],"type":"topic","title":"GesturedeckMedia","url":"\/documentation\/gesturedeckios\/gesturedeckmedia","kind":"symbol","role":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/gesturedeckMediaOverlay":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"gesturedeckMediaOverlay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay","text":"GesturedeckMediaOverlay","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The overlay view that displays media-related gestures.","type":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/gesturedeckMediaOverlay","navigatorTitle":[{"kind":"identifier","text":"gesturedeckMediaOverlay"}],"type":"topic","title":"gesturedeckMediaOverlay","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/gesturedeckmediaoverlay","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"gesturedeckMediaOverlay","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"gesturedeckMediaOverlay","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"GesturedeckMediaOverlay","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"kind":"text","text":" * "},{"kind":"identifier","text":"gesturedeckMediaOverlay"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title","value":"GesturedeckMediaOverlay"},{"value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments"},{"value":"GesturedeckMedia","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments","op":"replace","value":[{"text":"GesturedeckMedia","kind":"identifier"}]},{"value":"gesturedeckMediaOverlay","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1gesturedeckMediaOverlay\/title"},{"value":[{"kind":"identifier","text":"gesturedeckMediaOverlay"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1gesturedeckMediaOverlay\/fragments"}]}]}