{"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"tapAction"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = {\n            guard Bundle.main.infoDictionary?[\"NSAppleMusicUsageDescription\"] != nil else {\n                print(\"NSAppleMusicUsageDescription key not present\")\n                return\n            }\n            let audioSession = AVAudioSession.sharedInstance()\n            if MPMusicPlayerController.systemMusicPlayer.playbackState == .playing {\n                MPMusicPlayerController.systemMusicPlayer.pause()\n            } else if MPMusicPlayerController.systemMusicPlayer.playbackState == .paused {\n                MPMusicPlayerController.systemMusicPlayer.play()\n            } else if audioSession.secondaryAudioShouldBeSilencedHint {\n                DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) {  \n                    try? audioSession.setActive(true, options: .notifyOthersOnDeactivation)\n                }\n            } else {\n                try? audioSession.setActive(false, options: .notifyOthersOnDeactivation)\n            }\n        }, "},{"kind":"externalParam","text":"swipeLeftAction"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = {\n            guard Bundle.main.infoDictionary?[\"NSAppleMusicUsageDescription\"] != nil else {\n                print(\"NSAppleMusicUsageDescription key not present\")\n                return\n            }\n            if MPMusicPlayerController.systemMusicPlayer.playbackState == .playing {\n                MPMusicPlayerController.systemMusicPlayer.skipToPreviousItem()\n            }\n        }, ","kind":"text"},{"text":"swipeRightAction","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = {\n            guard Bundle.main.infoDictionary?[\"NSAppleMusicUsageDescription\"] != nil else {\n                print(\"NSAppleMusicUsageDescription key not present\")\n                return\n            }\n            if MPMusicPlayerController.systemMusicPlayer.playbackState == .playing {\n                MPMusicPlayerController.systemMusicPlayer.skipToNextItem()\n            }\n        }, ","kind":"text"},{"text":"panAction","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"text":"UIPanGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = { _ in }, ","kind":"text"},{"text":"panSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","text":"PanSensitivity"},{"kind":"text","text":" = .medium, "},{"kind":"externalParam","text":"longPressAction"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sender"},{"text":": ","kind":"text"},{"text":"UILongPressGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")? = { _ in }, ","kind":"text"},{"kind":"externalParam","text":"autoStart"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"gesturedeckMediaOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay","text":"GesturedeckMediaOverlay","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay"},{"kind":"text","text":"? = GesturedeckMediaOverlay(), "},{"kind":"externalParam","text":"activationKey"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller on which to add the gesture recognizer. Defaults to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"on"},{"content":[{"inlineContent":[{"text":"The action to perform when the user taps the screen. Defaults to play\/pause. Set to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" to disable.","type":"text"}],"type":"paragraph"}],"name":"tapAction"},{"content":[{"inlineContent":[{"type":"text","text":"The action to perform when the user swipes left. Defaults to skip previous. Set to "},{"type":"codeVoice","code":"nil"},{"text":" to disable.","type":"text"}],"type":"paragraph"}],"name":"swipeLeftAction"},{"name":"swipeRightAction","content":[{"type":"paragraph","inlineContent":[{"text":"The action to perform when the user swipes right. Defaults to skip next. Set to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" to disable.","type":"text"}]}]},{"name":"panAction","content":[{"inlineContent":[{"type":"text","text":"The action to perform when the user pans the screen. Defaults to volume change. Set to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" to disable."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The sensitivity of the pan gestures. Defaults to "},{"type":"codeVoice","code":".medium"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"panSensitivity"},{"name":"longPressAction","content":[{"inlineContent":[{"text":"The action to perform when the user long presses the screen. Defaults to showing the overlay. Set to ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" to disable."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A boolean indicating whether to automatically start recognizing gestures after initialization. Defaults to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"autoStart"},{"name":"gesturedeckMediaOverlay","content":[{"type":"paragraph","inlineContent":[{"text":"The overlay view that displays media-related gestures. Defaults to standard GesturedeckMediaOverlay. When using an activation key, can be set  to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" to not appear.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional activation key to remove watermarks. If not provided, Gesturedeck will present a watermark. Defaults to "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"activationKey"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Initializes a new instance of GesturedeckMedia."},{"text":" ","type":"text"},{"text":"You can initialize GesturedeckMedia without any arguments and have start\/stop, skip next\/previous and volume up\/down work out of the box.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:","kind":"identifier"}],"title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)","externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMedia(im)initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:","role":"symbol","modules":[{"name":"GesturedeckiOS"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?, ","kind":"text"},{"text":"tapAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"swipeLeftAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"swipeRightAction","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"panAction"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"text":"UIPanGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"panSensitivity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","text":"PanSensitivity","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"longPressAction","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"autoStart","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"gesturedeckMediaOverlay"},{"kind":"text","text":": "},{"text":"GesturedeckMediaOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"text":"?, ","kind":"text"},{"text":"activationKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:pansensitivity:longpressaction:autostart:gesturedeckmediaoverlay:activationkey:)"]},{"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:pansensitivity:longpressaction:autostart:gesturedeckmediaoverlay:activationkey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)":{"role":"symbol","title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:pansensitivity:longpressaction:autostart:gesturedeckmediaoverlay:activationkey:)","navigatorTitle":[{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:"}],"abstract":[{"type":"text","text":"Initializes a new instance of GesturedeckMedia."},{"text":" ","type":"text"},{"text":"You can initialize GesturedeckMedia without any arguments and have start\/stop, skip next\/previous and volume up\/down work out of the box.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"tapAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"swipeLeftAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"panAction"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIPanGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"panSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","text":"PanSensitivity"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"longPressAction"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"sender"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","text":"UILongPressGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"autoStart"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"gesturedeckMediaOverlay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GesturedeckMediaOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"activationKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"navigatorTitle":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","title":"GesturedeckMediaOverlay","url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/PanSensitivity":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PanSensitivity","kind":"identifier"}],"title":"PanSensitivity","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity","navigatorTitle":[{"kind":"identifier","text":"PanSensitivity"}],"url":"\/documentation\/gesturedeckios\/pansensitivity","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","kind":"symbol","url":"\/documentation\/gesturedeckios","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"role":"symbol","abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GesturedeckMedia","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GesturedeckMedia"}],"kind":"symbol","type":"topic","title":"GesturedeckMedia","url":"\/documentation\/gesturedeckios\/gesturedeckmedia"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initOn:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":" *) ","kind":"text"},{"text":"on","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tapAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")()) "},{"text":"tapAction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"swipeLeftAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")()) ","kind":"text"},{"text":"swipeLeftAction","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeRightAction:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"text":"swipeRightAction","kind":"internalParam"},{"kind":"text","text":" "},{"text":"panAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"panAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"panSensitivity:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@GesturedeckiOS@E@PanSensitivity","text":"PanSensitivity","kind":"typeIdentifier","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/PanSensitivity"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"panSensitivity"},{"text":" ","kind":"text"},{"text":"longPressAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","kind":"typeIdentifier","text":"UILongPressGestureRecognizer"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"longPressAction","kind":"internalParam"},{"kind":"text","text":" "},{"text":"autoStart:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"autoStart","kind":"internalParam"},{"kind":"text","text":" "},{"text":"gesturedeckMediaOverlay:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","kind":"typeIdentifier","text":"GesturedeckMediaOverlay","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"gesturedeckMediaOverlay"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activationKey:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"activationKey","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The view controller on which to add the gesture recognizer. Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"on"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The action to perform when the user taps the screen. Defaults to play\/pause. Set to ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" to disable."}]}],"name":"tapAction"},{"name":"swipeLeftAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to perform when the user swipes left. Defaults to skip previous. Set to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" to disable."}]}]},{"name":"swipeRightAction","content":[{"inlineContent":[{"text":"The action to perform when the user swipes right. Defaults to skip next. Set to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" to disable.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to perform when the user pans the screen. Defaults to volume change. Set to "},{"type":"codeVoice","code":"nil"},{"text":" to disable.","type":"text"}]}],"name":"panAction"},{"name":"panSensitivity","content":[{"inlineContent":[{"type":"text","text":"The sensitivity of the pan gestures. Defaults to "},{"code":".medium","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"longPressAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to perform when the user long presses the screen. Defaults to showing the overlay. Set to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" to disable."}]}]},{"name":"autoStart","content":[{"inlineContent":[{"type":"text","text":"A boolean indicating whether to automatically start recognizing gestures after initialization. Defaults to "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"gesturedeckMediaOverlay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The overlay view that displays media-related gestures. Defaults to standard GesturedeckMediaOverlay. When using an activation key, can be set  to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" to not appear."}]}]},{"name":"activationKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional activation key to remove watermarks. If not provided, Gesturedeck will present a watermark. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:panSensitivity:longPressAction:autoStart:gesturedeckMediaOverlay:activationKey:"}]},{"value":"GesturedeckMediaOverlay","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments","value":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}]},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/navigatorTitle","value":[{"text":"GesturedeckMediaOverlay","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PanSensitivity","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/fragments","value":[{"text":"PanSensitivity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1PanSensitivity\/navigatorTitle","value":[{"kind":"identifier","text":"PanSensitivity"}],"op":"replace"},{"value":"GesturedeckMedia","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title"},{"value":[{"kind":"identifier","text":"GesturedeckMedia"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments"},{"value":[{"text":"GesturedeckMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}