{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"tapAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"panAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil, "},{"kind":"externalParam","text":"activationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"autoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"gesturedeckMediaOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay","text":"GesturedeckMediaOverlay"},{"kind":"text","text":" = GesturedeckMediaOverlay())"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"on","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller on which to add the gesture recognizer."}]}]},{"name":"tapAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to perform when the user taps the screen."}]}]},{"name":"swipeLeftAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to perform when the user swipes left."}]}]},{"name":"swipeRightAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to perform when the user swipes right."}]}]},{"name":"panAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to perform when the user pans the screen."}]}]},{"name":"longPressAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to perform when the user long presses the screen."}]}]},{"name":"activationKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The activation key for the app."}]}]},{"name":"gesturedeckMediaOverlay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The overlay view that displays media-related gestures."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:longpressaction:activationkey:autostart:gesturedeckmediaoverlay:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:longpressaction:activationkey:autostart:gesturedeckmediaoverlay:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new instance of GesturedeckMedia."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tapAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"panAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"activationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gesturedeckMediaOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GesturedeckMediaOverlay","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"kind":"text","text":")"}],"title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMedia(im)initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:","modules":[{"name":"GesturedeckiOS"}],"navigatorTitle":[{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:"}]},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"]]},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:)":{"role":"symbol","title":"init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tapAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeLeftAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"swipeRightAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"panAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPanGestureRecognizer","preciseIdentifier":"c:objc(cs)UIPanGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"longPressAction"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"activationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"autoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gesturedeckMediaOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GesturedeckMediaOverlay","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new instance of GesturedeckMedia."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/init(on:tapaction:swipeleftaction:swiperightaction:panaction:longpressaction:activationkey:autostart:gesturedeckmediaoverlay:)"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMediaOverlay":{"role":"symbol","title":"GesturedeckMediaOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"abstract":[{"type":"text","text":"A struct that represents the media overlay for Gesturedeck."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmediaoverlay"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"role":"symbol","title":"GesturedeckMedia","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GesturedeckMedia"}],"abstract":[{"type":"text","text":"A subclass of Gesturedeck that adds media-related gestures."}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GesturedeckMedia"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","title":"GesturedeckiOS","abstract":[],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","kind":"symbol","type":"topic","url":"\/documentation\/gesturedeckios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initOn:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"on"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tapAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeLeftAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"swipeLeftAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeRightAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"swipeRightAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"panAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(UIPanGestureRecognizer *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIPanGestureRecognizer)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"panAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"longPressAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(UILongPressGestureRecognizer *)","preciseIdentifier":"c:BFv(#*$objc(cs)UILongPressGestureRecognizer)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"longPressAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"activationKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"activationKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoStart:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoStart"},{"kind":"text","text":" "},{"kind":"identifier","text":"gesturedeckMediaOverlay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMediaOverlay","preciseIdentifier":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMediaOverlay","text":"GesturedeckMediaOverlay"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gesturedeckMediaOverlay"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:)\/title","value":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1init(on:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOn:tapAction:swipeLeftAction:swipeRightAction:panAction:longPressAction:activationKey:autoStart:gesturedeckMediaOverlay:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/title","value":"GesturedeckMediaOverlay"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMediaOverlay\/fragments","value":[{"kind":"identifier","text":"GesturedeckMediaOverlay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title","value":"GesturedeckMedia"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments","value":[{"kind":"identifier","text":"GesturedeckMedia"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}