{"sections":[],"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/isActive","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMedia(py)isActive","symbolKind":"property","title":"isActive","navigatorTitle":[{"kind":"identifier","text":"isActive"}],"roleHeading":"Instance Property","modules":[{"name":"GesturedeckiOS"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/isactive"]},{"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/isactive"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Determines whether the gesture recognizer is active.","type":"text"}],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/isActive":{"navigatorTitle":[{"kind":"identifier","text":"isActive"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/isactive","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isActive","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"isActive","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/isActive","abstract":[{"type":"text","text":"Determines whether the gesture recognizer is active."}],"role":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"role":"symbol","abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GesturedeckMedia","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GesturedeckMedia"}],"kind":"symbol","type":"topic","title":"GesturedeckMedia","url":"\/documentation\/gesturedeckios\/gesturedeckmedia"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","kind":"symbol","url":"\/documentation\/gesturedeckios","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"title":"GesturedeckiOS"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"isActive","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isActive"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"isActive","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"isActive","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1isActive\/title"},{"value":[{"text":"isActive","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1isActive\/fragments"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title","op":"replace","value":"GesturedeckMedia"},{"value":[{"kind":"identifier","text":"GesturedeckMedia"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/navigatorTitle","value":[{"text":"GesturedeckMedia","kind":"identifier"}]}]}]}