{"abstract":[{"type":"text","text":"A closure that is called when a long press gesture is recognized."}],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"longPressAction","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"gestureRecognizer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UILongPressGestureRecognizer","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/longPressAction","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/longpressaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/longpressaction"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","title":"longPressAction","symbolKind":"property","navigatorTitle":[{"text":"longPressAction","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"longPressAction","kind":"identifier"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer","text":"UILongPressGestureRecognizer"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMedia(py)longPressAction","modules":[{"name":"GesturedeckiOS"}]},"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"type":"topic","role":"collection","abstract":[],"kind":"symbol","url":"\/documentation\/gesturedeckios","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GesturedeckMedia"}],"abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","navigatorTitle":[{"text":"GesturedeckMedia","kind":"identifier"}],"type":"topic","title":"GesturedeckMedia","url":"\/documentation\/gesturedeckios\/gesturedeckmedia","kind":"symbol","role":"symbol"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/longPressAction":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"longPressAction","kind":"identifier"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"text":": ","kind":"text"},{"text":"UILongPressGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILongPressGestureRecognizer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?","kind":"text"}],"title":"longPressAction","navigatorTitle":[{"text":"longPressAction","kind":"identifier"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/longpressaction","abstract":[{"type":"text","text":"A closure that is called when a long press gesture is recognized."}],"type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/longPressAction","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"longPressAction","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"longPressAction"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)UILongPressGestureRecognizer)","text":"void (^)(UILongPressGestureRecognizer *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"longPressAction","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title","value":"GesturedeckMedia","op":"replace"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments","op":"replace","value":[{"text":"GesturedeckMedia","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1longPressAction\/title","op":"replace","value":"longPressAction"},{"op":"replace","value":[{"text":"longPressAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1longPressAction\/fragments"}]}]}