{"variants":[{"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/start()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/start()"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"GesturedeckiOS"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMedia(im)start","symbolKind":"method","role":"symbol","title":"start()","navigatorTitle":[{"kind":"identifier","text":"start"}]},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/start()","interfaceLanguage":"swift"},"abstract":[{"text":"Starts the gesture recognizer.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"]]},"sections":[],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"role":"collection","kind":"symbol","url":"\/documentation\/gesturedeckios","type":"topic","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"title":"GesturedeckiOS"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"role":"symbol","abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GesturedeckMedia","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GesturedeckMedia"}],"kind":"symbol","type":"topic","title":"GesturedeckMedia","url":"\/documentation\/gesturedeckios\/gesturedeckmedia"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/start()":{"abstract":[{"type":"text","text":"Starts the gesture recognizer."}],"role":"symbol","title":"start()","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/start()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/start()","navigatorTitle":[{"text":"start","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"start"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"start"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title","op":"replace","value":"GesturedeckMedia"},{"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments","value":[{"text":"GesturedeckMedia","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/navigatorTitle","op":"replace","value":[{"text":"GesturedeckMedia","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1start()\/title","value":"start","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1start()\/fragments"}]}]}