{"abstract":[{"type":"text","text":"A closure that is called when a left swipe gesture is recognized."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/swipeleftaction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gesturedeckios\/gesturedeckmedia\/swipeleftaction"]}],"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"GesturedeckiOS"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"swipeLeftAction","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"role":"symbol","title":"swipeLeftAction","roleHeading":"Instance Property","externalID":"c:@M@GesturedeckiOS@objc(cs)GesturedeckMedia(py)swipeLeftAction","navigatorTitle":[{"kind":"identifier","text":"swipeLeftAction"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia"]]},"identifier":{"url":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/swipeLeftAction","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeLeftAction"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia/swipeLeftAction":{"kind":"symbol","url":"\/documentation\/gesturedeckios\/gesturedeckmedia\/swipeleftaction","navigatorTitle":[{"text":"swipeLeftAction","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swipeLeftAction"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"title":"swipeLeftAction","type":"topic","abstract":[{"type":"text","text":"A closure that is called when a left swipe gesture is recognized."}],"role":"symbol","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia\/swipeLeftAction"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS":{"title":"GesturedeckiOS","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS","abstract":[],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/gesturedeckios"},"doc://com.navideck.gesturedeck-ios/documentation/GesturedeckiOS/GesturedeckMedia":{"abstract":[{"text":"A subclass of Gesturedeck that provides media-specific functionality such as volume control and media playback actions.","type":"text"}],"url":"\/documentation\/gesturedeckios\/gesturedeckmedia","identifier":"doc:\/\/com.navideck.gesturedeck-ios\/documentation\/GesturedeckiOS\/GesturedeckMedia","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GesturedeckMedia","kind":"identifier"}],"type":"topic","title":"GesturedeckMedia","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"GesturedeckMedia","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"swipeLeftAction","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"swipeLeftAction","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"void (^)(void)","preciseIdentifier":"c:BFv()","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"swipeLeftAction","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"swipeLeftAction","op":"replace","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1swipeLeftAction\/title"},{"op":"replace","value":[{"kind":"identifier","text":"swipeLeftAction"}],"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia~1swipeLeftAction\/fragments"},{"op":"replace","value":"GesturedeckMedia","path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/title"},{"path":"\/references\/doc:~1~1com.navideck.gesturedeck-ios~1documentation~1GesturedeckiOS~1GesturedeckMedia\/fragments","value":[{"kind":"identifier","text":"GesturedeckMedia"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}